---
name: 'Brainfuck install'
author: Yevhen Fabizhevskyi
description: 'This GitHub action installs one of the brainfuck interpreters called brainfucky.'
branding:
  icon: chevrons-right
  color: gray-dark
inputs:
  version:
    description: 'Brainfucky library version.'
    required: false
    default: null
runs:
  using: 'node12'
  main: 'dist/index.js'
