---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          ref: v1.0.2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']    
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fabasoad/setup-brainfuck-action@v1.0.2
        with:
          version: 0.1.dev1
      - name: Hello World
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          touch ./hello-world.bf
          echo "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++" > ./hello-world.bf
          echo "+.------.--------.>>+.>++." >> ./hello-world.bf
          output=$(brainfucky --file ./hello-world.bf)
          rm ./hello-world.bf
          [[ "${output:32:12}" == "Hello World!" ]] || exit 1;
      - name: Hello World
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          New-Item -Path . -Name "hello-world.bf" -ItemType "file" -Value "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++"
          Add-Content hello-world.bf "+.------.--------.>>+.>++."
          $Output = (brainfucky --file hello-world.bf) | Out-String
          Remove-Item hello-world.bf
          if ($Output -ne 'Hello World!') exit 1
