---
name: CI (latest)

on: push

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          ref: v1.0.2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    strategy:
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']    
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fabasoad/setup-brainfuck-action@v1.0.2
        with:
          version: 0.1.dev1
      - name: Hello World
        run: |
          touch ./hello-world.bf
          echo "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++" > ./hello-world.bf
          echo "+.------.--------.>>+.>++." >> ./hello-world.bf
          brainfucky --file /hello-world.bf | grep -q 'Hello World!' || exit 1;
          rm ./hello-world.bf
