---
name: CI (master)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']    
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: ./
        with:
          version: 0.1.dev1
      - name: Hello World
        run: |
          touch ./hello-world.bf
          echo "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++" > ./hello-world.bf
          echo "+.------.--------.>>+.>++." >> ./hello-world.bf
          output=$(brainfucky --file ./hello-world.bf)
          [[ "${output:32:12}" == "Hello World!" ]] || exit 1;
          rm ./hello-world.bf
